services:
  - type: web
    name: portfolio-jsp-0.0.1-SNAPSHOT
    env: docker
    dockerfilePath: ./Dockerfile
    # buildCommand: "./mvnw clean package"
    # startCommand: "" # Render will auto-deploy WAR
    # startCommand: java -jar my-custom-start.jar
    plan: free
    region: oregon
    autoDeploy: true
    # envVars:
    #   - key: JAVA_OPTS
    #     value: "-Xms256m -Xmx512m"
