AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.jiocoders.LambdaHandler
      Runtime: java17
      CodeUri: target/portfolio-jsp-0.0.1-SNAPSHOT.jar
      MemorySize: 1024
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
